### ISSUE TITLE
With my strong background and technical skills, I am excited to join your team and make a significant impact.

### ISSUE THREAD

**Issue by kentaurse** [sunformsdk/sunform#2]
Hi, I'm Ethan Tan, an expert in web full-stack and blockchain development with over 8 years of experience. I specialize in crafting durable, scalable web applications and innovative blockchain solutions. My proficiency in React.js, Vue.js, and Next.js, along with my expertise in Solidity for smart contracts, ensures I deliver superior, secure, and efficient solutions designed to meet your unique objectives.

**Comment by hydroperfox** [comment]
Hi, Ethan! Your talents are a great plus! I am inviting you as a member to the organization!

**Comment by kentaurse** [comment]
thank you

**Comment by hydroperfox** [comment]
No problem. I am still deciding what I'll do about the platform.

Actually Adobe AIR (derivative from Adobe Flash for native applications) includes almost everything I intend, except that:

* The Flash Platform API for display objects does not include a registration point that is crucial for common rotations around the center axis.
* The Adobe AIR SDK contains a MXML compiler that contains a few fundamental code base limitations that difficults certain features being added and also difficults the direct compiler usage when depending in, for example, common libraries (whether native extensions or not).

HARMAN (a Samsung company) is actually the one responsible for maintaining Adobe AIR after an Adobe announcement around 2020.

The AIR SDK contains the Flex compiler (the MXML compiler), but I am not sure where it is heading right now.

Anyways, I have contacted the office near me to see if there is a possibility of a new MXML compiler to see if we could skip this complex API that takes long to go.

**Comment by kentaurse** [comment]
thank you for your reply
I want to help you

**Comment by hydroperfox** [comment]
Ah, you motivate me! I'm guessing we'll have no luck with Adobe and Samsung...

Yeah, not sure now :-/ I have sent a SMS message to the Sul office (given that I am in Centro Oeste), but guess there is no opportunity for a MXML compiler in the HARMAN subcompany as part of Samsung (I guess). I'm still waiting a reply, but not sure; these are the first times I'm dealing with phone chips for communication.

We could build one in our own for Adobe AIR, but without an outcome it's not that worthy, given that any good compiler is complex and full of details to organize. I'm guessing going open source and giving things for free is waste of intellectual property.

**Comment by hydroperfox** [comment]
Right now I have founded:

* The ActionScript 3 language series parser
* The ActionScript 3 language database

The actual compiler includes:

* A strict verifier
  * Performs control flow analysis for example in return paths
* A code generator
  * Performs control flow analysis to organize execution cycle blocks and generate low-level blocks using jump instructions

**Comment by kentaurse** [comment]
I understand

**Comment by kentaurse** [comment]
So how can I help you

**Comment by kentaurse** [comment]
I think so
For a more active community, please contact us using the contact details below.

-Contact Info
skype: https://join.skype.com/invite/FVUI6gLcYgAE
telegram: https://t.me/ethantan1116k
slack: https://join.slack.com/t/ksc-xme4972/shared_invite/zt-2ld45idp2-G9HkxP_wX4ctwQshyPM7Ig
discord: https://discord.gg/VxnfdY4bS4
